### ISSUE TITLE
YPLibrarySelection cannot store it own croprect in multi-selection

### ISSUE THREAD

**Issue by wzio** [Yummypets/YPImagePicker#409]
**Describe the bug**
When multiple images are selected with different `croprect`, `YPLibrarySelection` does not correctly store the `scrollViewContentOffset`,` scrollViewZoomScale`, `cropRect` properties, but it will take the value of the `YPLibraryView`'s `assetZoomableView` and `currentCropRect` properties.

**To Reproduce**
1. Install the exmaple project
2. selected three image and scroll a image to get a different croprect
3. clicked and clicked the selected three images until you find that all the image has same croprect

**Expected behavior**
`YPLibrarySelection` should correctly store its own properties such as `croprect` and cannot be affected by `YPAssetZoomableView`. Attributes such as croprect of `YPAssetZoomableView`, may be another value of image

**Comment by carmelogallo** [comment]
Some problem here but only when I try to crop an image doing a zoom+scroll. Then if I choose another image and select back the one that I've edited, it will return to the original zoom+scroll. Any clue when this will be added?

[Screen Recording 2020-03-06 at 22.02.17.zip](https://github.com/Yummypets/YPImagePicker/files/4300388/Screen.Recording.2020-03-06.at.22.02.17.zip)

**Comment by carmelogallo** [comment]
@s4cha could you help here? This is a valid point that in my opinion should be fixed.

**Comment by wzio** [comment]
[fixed by this](https://github.com/Yummypets/YPImagePicker/pull/411), this will be closed

**Comment by carmelogallo** [comment]
@wzio Is it fixed though? In which version?I still don't see the fix.

**Comment by JayMehta97** [comment]
@wzio I can't see this issue being solved by current master branch code
