### ISSUE TITLE
No active and enabled video connection

### ISSUE THREAD

**Issue by mdfalcon104** [Yummypets/YPImagePicker#610]
I got this crash log on iPhone 5s 

 1.0.1 (1.0.1)
 12.4.9 (16H5)
 iPhone 5s
 Nov 28, 2020, 4:42:49 PM

```
Fatal Exception: NSGenericException
*** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] No active and enabled video connection
closure #1 in YPCameraVC.shotButtonTapped()
```

**Comment by Husseinhj** [comment]
same exception

**Comment by NikKovIos** [comment]
Related https://github.com/Yummypets/YPImagePicker/issues/472

**Comment by NikKovIos** [comment]
Should be fixed in https://github.com/Yummypets/YPImagePicker/releases/tag/5.2.1
Feel free to open new issue if found.

**Comment by parham-up** [comment]
Fatal Exception: NSInvalidArgumentException
*** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] No active and enabled video connection
Still happening on 5.2.2

**Comment by yannisroy** [comment]
Same here with version 5.2.2

**Comment by nandawperdana** [comment]
still happening on 5.2.2 for me too
