### ISSUE TITLE
Crash on YPLibraryVC.swift line 471

### ISSUE THREAD

**Issue by majid701** [Yummypets/YPImagePicker#637]
I have not been able to reproduce this one. Not that common but happens sometimes:
100% iphone devices
100% iOS 14

**Stacktrace:**

**Crashed: com.apple.root.user-initiated-qos
EXC_BREAKPOINT 0x00000001887d5fb0**

Crashed: com.apple.root.user-initiated-qos
0  libswiftCore.dylib             0x1887d5fb0 _assertionFailure(_:_:file:line:flags:) + 488
1  YPImagePicker                  0x1047b27bc closure #1 in YPLibraryVC.selectedMedia(photoCallback:videoCallback:multipleItemsCallback:) + 471 (YPLibraryVC.swift:471)
2  YPImagePicker                  0x1047d7010 thunk for @escaping @callee_guaranteed () -> () + 4404916240 (<compiler-generated>:4404916240)
3  libdispatch.dylib              0x184a21298 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x184a22280 _dispatch_client_callout + 16
5  libdispatch.dylib              0x1849d4254 _dispatch_root_queue_drain + 688
6  libdispatch.dylib              0x1849d48e4 _dispatch_worker_thread2 + 124
7  libsystem_pthread.dylib        0x1cab57568 _pthread_wqthread + 212
8  libsystem_pthread.dylib        0x1cab5a874 start_wqthread + 8

**Comment by 338drive** [comment]
I have same issue. Can't reproduce but some of users have this problem 
iOS: 14.4.1 
Device: iPhone 6s Plus

Crashed: com.apple.root.user-initiated-qos
0  libswiftCore.dylib             0x18e556aa8 _assertionFailure(_:_:file:line:flags:) + 488
1  YPImagePicker                  0x104c1a7bc closure #1 in YPLibraryVC.selectedMedia(photoCallback:videoCallback:multipleItemsCallback:) + 471 (YPLibraryVC.swift:471)
2  YPImagePicker                  0x104c3f010 thunk for @escaping @callee_guaranteed () -> () + 4410912784 (<compiler-generated>:4410912784)
3  libdispatch.dylib              0x18a769298 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x18a76a280 _dispatch_client_callout + 16
5  libdispatch.dylib              0x18a71c074 _dispatch_root_queue_drain + 688
6  libdispatch.dylib              0x18a71c704 _dispatch_worker_thread2 + 124
7  libsystem_pthread.dylib        0x1d3319568 _pthread_wqthread + 212
8  libsystem_pthread.dylib        0x1d331c874 start_wqthread + 8

**Comment by hansemannn** [comment]
Same here (multiple crashes, all iOS 14, iPhone 7 + X):
```
Crashed: com.apple.root.user-initiated-qos
0  libswiftCore.dylib             0x19319aaa8 _assertionFailure(_:_:file:line:flags:) + 488
1  YPImagePicker                  0x10625cb90 $s13YPImagePicker11YPLibraryVCC13selectedMedia13photoCallback05videoH0013multipleItemsH0yyAA12YPMediaPhotoCc_yAA0L5VideoCcySayAA0L4ItemOGctFyycfU_ + 4484
2  YPImagePicker                  0x10623dbd0 $sIeg_IeyB_TR + 20
3  libdispatch.dylib              0x18f3ad298 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x18f3ae280 _dispatch_client_callout + 16
5  libdispatch.dylib              0x18f360074 _dispatch_root_queue_drain + 688
6  libdispatch.dylib              0x18f360704 _dispatch_worker_thread2 + 124
7  libsystem_pthread.dylib        0x1d7f99568 _pthread_wqthread + 212
8  libsystem_pthread.dylib        0x1d7f9c874 start_wqthread + 8
```

**Comment by AndriiHanets** [comment]
Same random crashes

```
0  libswiftCore.dylib             0x1a2b57a18 _assertionFailure(_:_:file:line:flags:) + 492
1  YPImagePicker                  0x106055994 closure #1 in YPLibraryVC.selectedMedia(photoCallback:videoCallback:multipleItemsCallback:) + 478 (YPLibraryVC.swift:478)
2  YPImagePicker                  0x10607aefc thunk for @escaping @callee_guaranteed () -> () + 4438585084 (<compiler-generated>:4438585084)
3  libdispatch.dylib              0x19eb2024c _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x19eb21db0 _dispatch_client_callout + 20
5  libdispatch.dylib              0x19eb32a68 _dispatch_root_queue_drain + 656
6  libdispatch.dylib              0x19eb33120 _dispatch_worker_thread2 + 116
7  libsystem_pthread.dylib        0x1ea9dd7d8 _pthread_wqthread + 216
8  libsystem_pthread.dylib        0x1ea9e476c start_wqthread + 8
```

**Comment by chenium** [comment]
Has there been any progress regarding this crash? We're also receiving crash reports related to this and unable to reproduce the crash locally. My suspicion is that `self.selection`, a mutable container is being access through multiple threads raising a potential race condition. Any thoughts?

**Comment by NikKovIos** [comment]
@chenium I think you're right. Now I did replaced assert by log. That wouldn't fix the problem, but user stop crash.
If someone can reproduce it, please make a PR.
Related https://github.com/Yummypets/YPImagePicker/issues/668

**Comment by hansemannn** [comment]
Happy to sponsor a bug bounty for this. Anyone able to fix this?

**Comment by NikKovIos** [comment]
@hansemannn I can't reproduce it. Maybe you can fix it?

**Comment by hansemannn** [comment]
Unfortunately I wasn't ever able to reproduce it, I just noticed it via Crashlytics. I feel like it's some kind of threading issue or maybe #696, but I wasn't even able to reproduce that.

**Comment by NikKovIos** [comment]
@hansemannn so am I 🤷🏻‍♂️

**Comment by majid701** [comment]
@hansemannn @NikKovIos 
It happens when selecting multiple assets from the library and from data I received on the crashlytics dashboard it's happening 100% on iOS 14 and above. Looks like something is happening when user taps on the multiple selection button:

`Crashed: com.apple.main-thread
0  YPImagePicker                  0x3b1b0 YPLibraryVC.showMultipleSelection() + 182 (YPLibraryVC.swift:182)
1  YPImagePicker                  0x3aa18 YPLibraryVC.multipleSelectionButtonTapped() + 164 (YPLibraryVC.swift:164)
2  YPImagePicker                  0x3ac84 @objc YPLibraryVC.multipleSelectionButtonTapped() + 4335955076 (<compiler-generated>:4335955076)
`

Unfortunately I haven't been able to reproduce it but I will try again on my side and post any updates here.

**Comment by krzysiek84** [comment]
This happens from time to time to one of the users of my app.

I've got crash log from XCode. It crashes in `showMultipleSelection` and it shows the issue was because of "Unexpectedly found nil while implicitly unwrapping an Optional Value".
In this line:
`let asset = mediaManager.fetchResult[currentlySelectedIndex]`

So looks like fetchResult is nil. No idea though why this happens, how to replicate and what is the proper fix 🤷

**Comment by NikKovIos** [comment]
Tryed to fix it in beed49d4ac6f2a8fe260d461992b365c5e9eaf4f
You can try this commit and say if it help.

**Comment by NikKovIos** [comment]
Use https://github.com/Yummypets/YPImagePicker/releases/tag/5.2.1
Should be fixed there)

**Comment by krzysiek84** [comment]
@NikKovIos  Can confirm that i no longer see the crash in YPImagePicker when using 5.2.1 version 👍

**Comment by parham-up** [comment]
@NikKovIos I'm using 5.2.1 and still see the crash. Please see attached stack trace.
[com.ultimateperformance.trainer_issue_ef67adb9d411094f5197f118c6fa094b_crash_session_e88ac29f7c864df1badc153f2a4c341a_DNE_0_v2_stacktrace.txt](https://github.com/Yummypets/YPImagePicker/files/10695982/com.ultimateperformance.trainer_issue_ef67adb9d411094f5197f118c6fa094b_crash_session_e88ac29f7c864df1badc153f2a4c341a_DNE_0_v2_stacktrace.txt)

**Comment by paulsUsername** [comment]
Still seeing crash in 5.2.1:

Crashed: com.apple.root.user-initiated-qos
0  -                 0xbb7634 closure #1 in YPLibraryVC.selectedMedia(photoCallback:videoCallback:multipleItemsCallback:) + 4349097524 (<compiler-generated>:4349097524)
1 -                 0xb8ec34 thunk for @escaping @callee_guaranteed () -> () + 4348931124 (<compiler-generated>:4348931124)
2  libdispatch.dylib              0x2460 _dispatch_call_block_and_release + 32
3  libdispatch.dylib              0x3f88 _dispatch_client_callout + 20
4  libdispatch.dylib              0x15b8c _dispatch_root_queue_drain + 684
5  libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
6  libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
7  libsystem_pthread.dylib        0xb98 start_wqthread + 8
